//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.1
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.VSDesigner, 버전 4.0.30319.1에서 자동으로 생성되었습니다.
// 
#pragma warning disable 1591

namespace Function.uScm.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TDTServiceBinding", Namespace="urn:upn:tdt:wsdl:1")]
    public partial class UPNTDTService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback translateBinToCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback translateHexaToCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback translateTagIdToBinOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UPNTDTService() {
            this.Url = global::Function.uScm.Properties.Settings.Default.Function_uScm_WebReference_UPNTDTService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event translateBinToCodeCompletedEventHandler translateBinToCodeCompleted;
        
        /// <remarks/>
        public event translateHexaToCodeCompletedEventHandler translateHexaToCodeCompleted;
        
        /// <remarks/>
        public event translateTagIdToBinCompletedEventHandler translateTagIdToBinCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ResponseCode", Namespace="urn:upn:tdt:xsd:1")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("CodeResult", IsNullable=false)]
        public CodeResultType[] translateBinToCode([System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:upn:tdt:xsd:1")] [System.Xml.Serialization.XmlArrayItemAttribute("CodeSpec", IsNullable=false)] CodeSpecType[] RequestBinCode) {
            object[] results = this.Invoke("translateBinToCode", new object[] {
                        RequestBinCode});
            return ((CodeResultType[])(results[0]));
        }
        
        /// <remarks/>
        public void translateBinToCodeAsync(CodeSpecType[] RequestBinCode) {
            this.translateBinToCodeAsync(RequestBinCode, null);
        }
        
        /// <remarks/>
        public void translateBinToCodeAsync(CodeSpecType[] RequestBinCode, object userState) {
            if ((this.translateBinToCodeOperationCompleted == null)) {
                this.translateBinToCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OntranslateBinToCodeOperationCompleted);
            }
            this.InvokeAsync("translateBinToCode", new object[] {
                        RequestBinCode}, this.translateBinToCodeOperationCompleted, userState);
        }
        
        private void OntranslateBinToCodeOperationCompleted(object arg) {
            if ((this.translateBinToCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.translateBinToCodeCompleted(this, new translateBinToCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ResponseCode", Namespace="urn:upn:tdt:xsd:1")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("CodeResult", IsNullable=false)]
        public CodeResultType[] translateHexaToCode([System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:upn:tdt:xsd:1")] [System.Xml.Serialization.XmlArrayItemAttribute("CodeSpec", IsNullable=false)] CodeSpecType[] RequestHexaCode) {
            object[] results = this.Invoke("translateHexaToCode", new object[] {
                        RequestHexaCode});
            return ((CodeResultType[])(results[0]));
        }
        
        /// <remarks/>
        public void translateHexaToCodeAsync(CodeSpecType[] RequestHexaCode) {
            this.translateHexaToCodeAsync(RequestHexaCode, null);
        }
        
        /// <remarks/>
        public void translateHexaToCodeAsync(CodeSpecType[] RequestHexaCode, object userState) {
            if ((this.translateHexaToCodeOperationCompleted == null)) {
                this.translateHexaToCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OntranslateHexaToCodeOperationCompleted);
            }
            this.InvokeAsync("translateHexaToCode", new object[] {
                        RequestHexaCode}, this.translateHexaToCodeOperationCompleted, userState);
        }
        
        private void OntranslateHexaToCodeOperationCompleted(object arg) {
            if ((this.translateHexaToCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.translateHexaToCodeCompleted(this, new translateHexaToCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ResponseCode", Namespace="urn:upn:tdt:xsd:1")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("CodeResult", IsNullable=false)]
        public CodeResultType[] translateTagIdToBin([System.Xml.Serialization.XmlArrayAttribute(Namespace="urn:upn:tdt:xsd:1")] [System.Xml.Serialization.XmlArrayItemAttribute("CodeSpec", IsNullable=false)] CodeSpecType[] RequestTagIdBCode) {
            object[] results = this.Invoke("translateTagIdToBin", new object[] {
                        RequestTagIdBCode});
            return ((CodeResultType[])(results[0]));
        }
        
        /// <remarks/>
        public void translateTagIdToBinAsync(CodeSpecType[] RequestTagIdBCode) {
            this.translateTagIdToBinAsync(RequestTagIdBCode, null);
        }
        
        /// <remarks/>
        public void translateTagIdToBinAsync(CodeSpecType[] RequestTagIdBCode, object userState) {
            if ((this.translateTagIdToBinOperationCompleted == null)) {
                this.translateTagIdToBinOperationCompleted = new System.Threading.SendOrPostCallback(this.OntranslateTagIdToBinOperationCompleted);
            }
            this.InvokeAsync("translateTagIdToBin", new object[] {
                        RequestTagIdBCode}, this.translateTagIdToBinOperationCompleted, userState);
        }
        
        private void OntranslateTagIdToBinOperationCompleted(object arg) {
            if ((this.translateTagIdToBinCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.translateTagIdToBinCompleted(this, new translateTagIdToBinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:upn:tdt:xsd:1")]
    public partial class CodeSpecType {
        
        private string tagLengthField;
        
        private string codeStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string TagLength {
            get {
                return this.tagLengthField;
            }
            set {
                this.tagLengthField = value;
            }
        }
        
        /// <remarks/>
        public string CodeString {
            get {
                return this.codeStringField;
            }
            set {
                this.codeStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:upn:tdt:xsd:1")]
    public partial class CodeResultType {
        
        private string originalStringField;
        
        private string resultStringField;
        
        /// <remarks/>
        public string OriginalString {
            get {
                return this.originalStringField;
            }
            set {
                this.originalStringField = value;
            }
        }
        
        /// <remarks/>
        public string ResultString {
            get {
                return this.resultStringField;
            }
            set {
                this.resultStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void translateBinToCodeCompletedEventHandler(object sender, translateBinToCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class translateBinToCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal translateBinToCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CodeResultType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CodeResultType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void translateHexaToCodeCompletedEventHandler(object sender, translateHexaToCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class translateHexaToCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal translateHexaToCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CodeResultType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CodeResultType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void translateTagIdToBinCompletedEventHandler(object sender, translateTagIdToBinCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class translateTagIdToBinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal translateTagIdToBinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CodeResultType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CodeResultType[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591